# Generated by Django 3.1.4 on 2021-01-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210123_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='emp_id',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='order',
            name='organisation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
