# Generated by Django 3.1.4 on 2021-01-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210123_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_image',
            field=models.ImageField(default='', upload_to='shop/idImages'),
        ),
    ]
